# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20170327_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teachers_key',
            field=models.BooleanField(default=False),
        ),
    ]
