# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20170226_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection', models.CharField(max_length=100)),
                ('subsection_text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='algebraicsystem',
            old_name='section_name',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='numericsystem',
            old_name='section_name',
            new_name='section',
        ),
        migrations.AddField(
            model_name='numericsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.NumericSystem'),
        ),
    ]
