# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20170226_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgebraicSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection', models.CharField(max_length=200)),
                ('subsection_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='algebraicsystem',
            name='section',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='numericsection',
            name='subsection',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='numericsystem',
            name='section',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='algebraicsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.AlgebraicSystem'),
        ),
    ]
