# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20170312_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algebraicsection',
            old_name='section',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='algebraicsection',
            old_name='subsection',
            new_name='subsection_name',
        ),
        migrations.RenameField(
            model_name='algebraicsystem',
            old_name='section',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='numericsection',
            old_name='section',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='numericsection',
            old_name='subsection',
            new_name='subsection_name',
        ),
        migrations.RenameField(
            model_name='numericsystem',
            old_name='section',
            new_name='section_name',
        ),
    ]
