# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20170401_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algebraicsection',
            name='subsection_text',
        ),
        migrations.RemoveField(
            model_name='numericsection',
            name='subsection_text',
        ),
        migrations.AddField(
            model_name='algebraicsection',
            name='file_student',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algebraicsection',
            name='file_teacher',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numericsection',
            name='file_student',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numericsection',
            name='file_teacher',
            field=models.URLField(blank=True, null=True),
        ),
    ]
