# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_auto_20170401_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='algebraicsection',
            name='file',
            field=models.FileField(default='1.docx', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='algebraicsection',
            name='section_type',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numericsection',
            name='file',
            field=models.FileField(default='1.docx', null=True, upload_to='media/'),
        ),
    ]
