# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_auto_20170425_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algebraicsection',
            name='file',
        ),
        migrations.RemoveField(
            model_name='numericsection',
            name='file',
        ),
        migrations.AlterField(
            model_name='algebraicsection',
            name='section_type',
            field=models.BooleanField(default='1'),
        ),
    ]
