# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_auto_20170425_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgebraicSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AlgebraicSubsection',
            },
        ),
        migrations.AlterField(
            model_name='algebraicsection',
            name='section_type',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='algebraicsubsection',
            name='subsection_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.AlgebraicSection'),
        ),
    ]
