# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_auto_20170425_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='algebraicsubsection',
            name='subsection_sub',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
